export const types = {
    login: '[AUTH] Log In',
    logout: '[AUTH] Log Out',
    userRenew: '[AUTH] Renovar usuario',
    refreshTokenExpired: '[AUTH] Token expirado',

    abogados:'[APP] Lista abogados',
    subfases:'[APP] Lista subfases',
    delegados:'[APP] Lista delegados',
    clasesDocEntrada:'[APP] Lista clases de documentos de entrada',
    clasesDocSalida:'[APP] Lista clases de documentos de salida',
    tiposDanio:'[APP] Lista de tipos de danio',
    dependenciasMininter:'[APP] Lista de dependencias del MININTER',
    procuradores:'[APP] Lista de procuradores',
    departamentos:'[APP] Lista de departamentoss',
    distritosJudicial: '[APP] Lista de distritos judiciales',
    delitos: '[APP] Lista de delitos',
    tiposAudiencia: '[APP] Lista de tipos de audiencia',
    tiposPena: '[APP] Lista de tipos de pena',
    tiposSentencia: '[APP] Lista de tipos de sentencia',
    tiposRemitente: '[APP] Lista de tipos de Remitente',
    currentLegajoCod:'[CONSULTA LEGAJOS] Actualizar el codigo del legajo actual',
}